export const MUTATION_TYPES = {
    CHANGE_BUCKET: "CHANGE_BUCKET",
    CHANGE_BUCKETS: "CHANGE_BUCKETS",
    CHANGE_FILES: "CHANGE_FILES",
    CHANGE_LOADING: "CHANGE_LOADING",
    CHANGE_CURRENTPATH: "CHANGE_CURRENTPATH",
  };
  